# Generated by Django 2.1.4 on 2018-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titttle'),
        ),
    ]
