# Generated by Django 2.1.4 on 2018-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
